package com.NovaCraft.world.ancient_city;

import net.minecraft.world.gen.feature.*;
import net.minecraft.block.*;
import net.minecraft.world.*;
import java.util.*;
import com.NovaCraftBlocks.NovaCraftBlocks;
import net.minecraft.init.*;

public class AncientCitySculkPatchGen3 extends WorldGenerator
{
	public AncientCitySculkPatchGen3() {

	}

	private static final Block sculk_block = NovaCraftBlocks.sculk_block;
	private static final Block sculk_tulip = NovaCraftBlocks.sculk_tulip;
	private static final Block sculk_tendrils = NovaCraftBlocks.sculk_tendrils;
	private static final Block sculk_bush = NovaCraftBlocks.sculk_bush;
	private static final Block sculk_bloom = NovaCraftBlocks.sculk_bloom;
    
    public boolean generate(final World world, final Random random, final int i, final int j, final int k) {
    	
		world.setBlock(i + 9, j, k, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 1, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 2, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 3, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 4, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 5, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 6, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 7, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 8, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 9, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 10, sculk_block, 0, 2);
		world.setBlock(i + 0, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 11, sculk_block, 0, 2);
		world.setBlock(i + 0, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 12, sculk_block, 0, 2);
		world.setBlock(i + 0, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 13, sculk_block, 0, 2);
		world.setBlock(i + 0, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 14, sculk_block, 0, 2);
		world.setBlock(i + 0, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 15, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 28, j, k + 16, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 28, j, k + 17, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 28, j, k + 18, sculk_block, 0, 2);
		world.setBlock(i + 1, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 28, j, k + 19, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 27, j, k + 20, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 26, j, k + 21, sculk_block, 0, 2);
		world.setBlock(i + 2, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 25, j, k + 22, sculk_block, 0, 2);
		world.setBlock(i + 3, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 23, sculk_block, 0, 2);
		world.setBlock(i + 4, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 23, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 24, j, k + 24, sculk_block, 0, 2);
		world.setBlock(i + 5, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 22, j, k + 25, sculk_block, 0, 2);
		world.setBlock(i + 6, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 21, j, k + 26, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 20, j, k + 27, sculk_block, 0, 2);
		world.setBlock(i + 7, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 19, j, k + 28, sculk_block, 0, 2);
		world.setBlock(i + 8, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 9, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 10, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 11, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 12, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 13, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 14, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 15, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 16, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 17, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 18, j, k + 29, sculk_block, 0, 2);
		world.setBlock(i + 11, j + 1, k, sculk_bush, 0, 2);
		world.setBlock(i + 11, j + 1, k + 2, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 9, j + 1, k + 3, sculk_tendrils, 0, 2);
		world.setBlock(i + 13, j + 1, k + 3, sculk_tendrils, 0, 2);
		world.setBlock(i + 10, j + 1, k + 4, sculk_tulip, 0, 2);
		world.setBlock(i + 12, j + 1, k + 4, sculk_bush, 0, 2);
		world.setBlock(i + 15, j + 1, k + 4, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 7, j + 1, k + 5, sculk_tendrils, 0, 2);
		world.setBlock(i + 10, j + 1, k + 6, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 14, j + 1, k + 6, sculk_tendrils, 0, 2);
		world.setBlock(i + 16, j + 1, k + 6, sculk_tulip, 0, 2);
		world.setBlock(i + 6, j + 1, k + 7, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 5, j + 1, k + 8, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 8, j + 1, k + 8, sculk_tendrils, 0, 2);
		world.setBlock(i + 11, j + 1, k + 8, sculk_tendrils, 0, 2);
		world.setBlock(i + 17, j + 1, k + 8, sculk_bush, 0, 2);
		world.setBlock(i + 19, j + 1, k + 8, sculk_bush, 0, 2);
		world.setBlock(i + 11, j + 1, k + 9, sculk_bush, 0, 2);
		world.setBlock(i + 14, j + 1, k + 9, sculk_tulip, 0, 2);
		world.setBlock(i + 16, j + 1, k + 9, sculk_tendrils, 0, 2);
		world.setBlock(i + 18, j + 1, k + 9, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 6, j + 1, k + 10, sculk_tendrils, 0, 2);
		world.setBlock(i + 20, j + 1, k + 10, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 22, j + 1, k + 10, sculk_tulip, 0, 2);
		world.setBlock(i + 5, j + 1, k + 11, sculk_bush, 0, 2);
		world.setBlock(i + 10, j + 1, k + 11, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 13, j + 1, k + 11, sculk_bloom, 0, 2);
		world.setBlock(i + 19, j + 1, k + 11, sculk_tendrils, 0, 2);
		world.setBlock(i + 2, j + 1, k + 12, sculk_tulip, 0, 2);
		world.setBlock(i + 12, j + 1, k + 12, sculk_tendrils, 0, 2);
		world.setBlock(i + 16, j + 1, k + 12, sculk_tendrils, 0, 2);
		world.setBlock(i + 4, j + 1, k + 13, sculk_tendrils, 0, 2);
		world.setBlock(i + 7, j + 1, k + 13, sculk_bush, 0, 2);
		world.setBlock(i + 10, j + 1, k + 13, sculk_tulip, 0, 2);
		world.setBlock(i + 21, j + 1, k + 13, sculk_tendrils, 0, 2);
		world.setBlock(i + 22, j + 1, k + 13, sculk_tendrils, 0, 2);
		world.setBlock(i + 1, j + 1, k + 14, sculk_bush, 0, 2);
		world.setBlock(i + 5, j + 1, k + 14, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 8, j + 1, k + 14, sculk_tendrils, 0, 2);
		world.setBlock(i + 13, j + 1, k + 14, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 17, j + 1, k + 14, sculk_bush, 0, 2);
		world.setBlock(i + 20, j + 1, k + 14, sculk_bloom, 0, 2);
		world.setBlock(i + 24, j + 1, k + 14, sculk_bush, 0, 2);
		world.setBlock(i + 3, j + 1, k + 15, sculk_tendrils, 0, 2);
		world.setBlock(i + 6, j + 1, k + 15, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 12, j + 1, k + 15, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 14, j + 1, k + 15, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 17, j + 1, k + 15, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 19, j + 1, k + 15, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 20, j + 1, k + 15, sculk_bush, 0, 2);
		world.setBlock(i + 24, j + 1, k + 15, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 1, j + 1, k + 16, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 9, j + 1, k + 16, sculk_bush, 0, 2);
		world.setBlock(i + 10, j + 1, k + 16, sculk_bush, 0, 2);
		world.setBlock(i + 15, j + 1, k + 16, sculk_tulip, 0, 2);
		world.setBlock(i + 22, j + 1, k + 16, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 14, j + 1, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 20, j + 1, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 26, j + 1, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 27, j + 1, k + 17, sculk_bush, 0, 2);
		world.setBlock(i + 2, j + 1, k + 18, sculk_tulip, 0, 2);
		world.setBlock(i + 5, j + 1, k + 18, sculk_tendrils, 0, 2);
		world.setBlock(i + 9, j + 1, k + 18, sculk_bloom, 0, 2);
		world.setBlock(i + 10, j + 1, k + 18, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 1, k + 18, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 13, j + 1, k + 18, sculk_tendrils, 0, 2);
		world.setBlock(i + 23, j + 1, k + 18, sculk_bush, 0, 2);
		world.setBlock(i + 3, j + 1, k + 19, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 5, j + 1, k + 19, sculk_bush, 0, 2);
		world.setBlock(i + 7, j + 1, k + 19, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 15, j + 1, k + 19, sculk_bush, 0, 2);
		world.setBlock(i + 17, j + 1, k + 19, sculk_tendrils, 0, 2);
		world.setBlock(i + 18, j + 1, k + 19, sculk_tulip, 0, 2);
		world.setBlock(i + 23, j + 1, k + 19, sculk_tendrils, 0, 2);
		world.setBlock(i + 4, j + 1, k + 20, sculk_tendrils, 0, 2);
		world.setBlock(i + 15, j + 1, k + 20, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 19, j + 1, k + 20, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 21, j + 1, k + 20, sculk_tendrils, 0, 2);
		world.setBlock(i + 25, j + 1, k + 20, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 3, j + 1, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 4, j + 1, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 8, j + 1, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 10, j + 1, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 1, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 5, j + 1, k + 22, sculk_tulip, 0, 2);
		world.setBlock(i + 7, j + 1, k + 22, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 14, j + 1, k + 22, sculk_tendrils, 0, 2);
		world.setBlock(i + 10, j + 1, k + 23, sculk_bush, 0, 2);
		world.setBlock(i + 18, j + 1, k + 23, sculk_tendrils, 0, 2);
		world.setBlock(i + 19, j + 1, k + 23, sculk_tulip, 0, 2);
		world.setBlock(i + 21, j + 1, k + 23, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 23, j + 1, k + 23, sculk_bush, 0, 2);
		world.setBlock(i + 8, j + 1, k + 24, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 21, j + 1, k + 24, sculk_tendrils, 0, 2);
		world.setBlock(i + 6, j + 1, k + 25, sculk_tulip, 0, 2);
		world.setBlock(i + 9, j + 1, k + 25, sculk_tendrils, 0, 2);
		world.setBlock(i + 13, j + 1, k + 25, sculk_tendrils, 0, 2);
		world.setBlock(i + 15, j + 1, k + 25, sculk_bloom, 0, 2);
		world.setBlock(i + 17, j + 1, k + 25, sculk_bush, 0, 2);
		world.setBlock(i + 13, j + 1, k + 26, sculk_bush, 0, 2);
		world.setBlock(i + 16, j + 1, k + 26, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 17, j + 1, k + 26, sculk_tendrils, 0, 2);
		world.setBlock(i + 9, j + 1, k + 27, NovaCraftBlocks.sculk_spike, 1, 2);
		world.setBlock(i + 18, j + 1, k + 27, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 8, j + 1, k + 28, sculk_tendrils, 0, 2);
		world.setBlock(i + 10, j + 1, k + 28, sculk_tulip, 0, 2);
		world.setBlock(i + 11, j + 1, k + 28, NovaCraftBlocks.sculk_tentacle_2, 1, 2);
		world.setBlock(i + 13, j + 1, k + 28, sculk_tendrils, 0, 2);
		world.setBlock(i + 15, j + 1, k + 28, sculk_tulip, 0, 2);
		world.setBlock(i + 14, j + 2, k + 6, sculk_tendrils, 0, 2);
		world.setBlock(i + 8, j + 2, k + 8, sculk_tendrils, 0, 2);
		world.setBlock(i + 16, j + 2, k + 9, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 2, k + 12, sculk_tendrils, 0, 2);
		world.setBlock(i + 16, j + 2, k + 12, sculk_tendrils, 0, 2);
		world.setBlock(i + 21, j + 2, k + 13, sculk_tendrils, 0, 2);
		world.setBlock(i + 8, j + 2, k + 14, sculk_tendrils, 0, 2);
		world.setBlock(i + 14, j + 2, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 20, j + 2, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 26, j + 2, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 5, j + 2, k + 18, sculk_tendrils, 0, 2);
		world.setBlock(i + 17, j + 2, k + 19, sculk_tendrils, 0, 2);
		world.setBlock(i + 4, j + 2, k + 20, sculk_tendrils, 0, 2);
		world.setBlock(i + 21, j + 2, k + 20, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 2, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 18, j + 2, k + 23, sculk_tendrils, 0, 2);
		world.setBlock(i + 14, j + 3, k + 6, sculk_tendrils, 0, 2);
		world.setBlock(i + 8, j + 3, k + 8, sculk_tendrils, 0, 2);
		world.setBlock(i + 16, j + 3, k + 12, sculk_tendrils, 0, 2);
		world.setBlock(i + 8, j + 3, k + 14, sculk_tendrils, 0, 2);
		world.setBlock(i + 20, j + 3, k + 17, sculk_tendrils, 0, 2);
		world.setBlock(i + 5, j + 3, k + 18, sculk_tendrils, 0, 2);
		world.setBlock(i + 4, j + 3, k + 20, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 3, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 18, j + 3, k + 23, sculk_tendrils, 0, 2);
		world.setBlock(i + 14, j + 4, k + 6, sculk_tendrils, 0, 2);
		world.setBlock(i + 12, j + 4, k + 21, sculk_tendrils, 0, 2);
		world.setBlock(i + 18, j + 4, k + 23, sculk_tendrils, 0, 2);
    	
    	return true;
    }

}
